name: Build and Test Branch

on:
  workflow_dispatch:
  push:
    branches:
      - '**DAT-**'
jobs:
  build:
    name: Build & Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java for publishing to GitHub Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github
          server-username: USERNAME
          server-password: TOKEN

      - name: Build and Package
        run: mvn -B dependency:go-offline clean package -DskipTests=true

      - name: Tag Package For Development
        run: cp ./liquibase-core/target/liquibase-core-0-SNAPSHOT.jar ./target/DAT-11899-SNAPSHOT.jar

      - name: Deploy Artifact
        env:
          USERNAME: liquibot
          TOKEN: ${{ secrets.BOT_TOKEN }}
        run: mvn -B org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy-file -Dfile=DAT-11899-SNAPSHOT.jar