name: Cleanup on Branch Delete

on:
  workflow_dispatch:
  delete:
    branches:
      - '**DAT-**'
jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
    - name: Get Package Version
      uses: castlabs/get-package-version-id-action@v2.1
      id: version
      with:
        version: "${{ github.event.ref }}-SNAPSHOT"
    
    - name: Delete Packages
      if: ${{ steps.version.outputs.ids != '' }}
      run: |
        packages_to_delete=($( mvn -B exec:exec -Dexec.executable=echo -Dexec.args='###MODULE_GAV### ${project.groupId}:${project.artifactId}' | grep '###MODULE_GAV### ' | cut -f2 -d' ' ))
        echo "PACKAGES_TO_DELETE=$packages_to_delete" >> $GITHUB_ENV
        echo $packages_to_delete
        for package_name in "${packages_to_delete[@]}"
        do
          for version_id in ${{ steps.version.outputs.ids }}
          do
            curl -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.LIQUIBOT_LIQUIBASE_PAT }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/user/packages/maven/$package_name/versions/$version_id 
          done
        done 
