name: Cleanup Master Builds on Release Published

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  clean-master-builds:
    runs-on: ubuntu-22.04
    steps:
    - name: Get Package Names
      run: |
        packages_to_delete=($( mvn -B exec:exec -Dexec.executable=echo -Dexec.args='###MODULE_GAV### ${project.groupId}.${project.artifactId}' | grep '###MODULE_GAV### ' | cut -f2 -d' ' ))
        echo 'packages_to_delete=$packages_to_delete' >> "$GITHUB_ENV"

    - name: Delete Github Packages for Master/Main
      run: |
        packages_to_delete=${{ env.packages_to_delete }}
        for package_name in "${packages_to_delete[@]}"
        do
            curl -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.LIQUIBOT_LIQUIBASE_PAT }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/user/packages/maven/$package_name/versions/master-SNAPSHOT
        done
      
    - name: Delete artifact based off of branch and commit SHA
      run: |
        packages_to_delete=${{ env.packages_to_delete }}
        git_sha="(git rev-parse --short HEAD)-SNAPSHOT"
        echo $packages_to_delete
        for package_name in "${packages_to_delete[@]}"
        do
            curl -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.LIQUIBOT_LIQUIBASE_PAT }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/user/packages/maven/$package_name/versions/$git_sha
        done
 